downlinks:
    - Ethernet 1/1
rp_loopback_int: Loopback0
anycast_rp_loopback_int: Loopback1
bgp_loopback_int: Loopback2
rp_loopback_ip: 10.0.0.1/32
bgp_loopback_ip: 10.1.0.1/32
anycast_rp_loopback_ip: "{{ anycast_rp_ip }}"
as_number: 65501
