- hosts: "{{ leaves_group }}"
  vars_files:
    - ./vars_files/vxlan_config.yml
  name: Configuring hosts from "{{ leaves_group }}" group with leaf role
  gather_facts: no
  tasks:
    - name: Task that include leaf role
      include_role:
        name: leaf
        vars_from: "{{ leaves_group }}"
        apply:
          tags:
            - leaves
      tags:
        - always
        