- hosts: "{{ global_vars.vxlan_leaves }}"
  vars:
    global_vars: "{{ lookup('file','vxlan_config.cfg') | cfg2dict }}"
  name: Configuring hosts from "{{ global_vars.vxlan_leaves }}" group with leaf role
  gather_facts: no
  roles:
    - leaf


