- name: Send show run
  nxos_command:
    commands:
      - show run
  register: result_of_show_run
- debug:
    var: result_of_show_run
- name: Gathering facts
  nxos_facts:
    gather_subset: all
    gather_network_resources: all
  register: all_facts
- debug:
   var: all_facts

